# Generated by Django 3.2.7 on 2021-09-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'email': 'Enter a valid email address.'}, max_length=60, unique=True, verbose_name='email'),
        ),
    ]
