# Generated by Django 3.2.7 on 2021-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'email': ' a valid email address.'}, max_length=60, unique=True, verbose_name='email'),
        ),
    ]
